config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: "books#index"

  get 'books/:book_id/reserve', to: 'reservations#reserve', as: 'reserve_book'
  get 'books/:book_id/take', to: 'reservations#take', as: 'take_book'
  get 'books/:book_id/give_back', to: 'reservations#give_back', as: 'give_back_book'
  get 'books/:book_id/cancel_reservation', to: 'reservations#cancel', as: 'cancel_book_reservation'
  get 'books/filter', to: 'books#filter', as: 'filter'
  get 'users/:user_id/reservations', to: 'reservations#users_reservations', as: 'users_reservations'
  get 'google-isbn', to: 'google_books#show'
  
  get 'api/v1/books/lookup', to: 'api/v1/books#lookup'
  
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reservations
  has_many :borrowers, through: :reservations, source: :user
  belongs_to :category

  # statuses: AVAILABLE, TAKEN, RESERVED, EXPIRED, CANCELED, RETURNED

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.where(name: name).first_or_initialize
  end

  private

  def notify_user_caledar(reservation)
    UserCapendarNotifier.new(reservation.user).perform(reservation)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  require 'action_view'
  include ActionView::Helpers::DateHelper

  self.table_name = 'book_reservations'
  belongs_to :book
  belongs_to :user

  before_create :set_expiration
  before_update :set_expiration

  scope :active, -> { where(status: ['TAKEN', 'RESERVED']).order(created_at: :desc) }
  scope :completed, -> { where(status: 'RETURNED').order(created_at: :desc) }

  def taken?
    status == 'TAKEN'
  end

  def available?
    status == 'AVAILABLE'
  end

  def expires_in
    if (taken? || available?) && expires_at
      if expires_at < Time.now
        "#{expires_at.to_date} (expired #{distance_of_time_in_words(Time.now, expires_at)} ago)"
      else
        "#{expires_at.to_date} (#{distance_of_time_in_words(Time.now, expires_at)} left)"
      end
    else
      "-"
    end
  end

  private

  def set_expiration
    if taken?
      self.expires_at = Time.now + 2.weeks
    elsif available?
      self.expires_at = Time.now + 1.day
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :reservations

  
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
       email: data['email'],
       password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
  	class BaseController < ActionController::API
  	  before_action :check_login

  	  private

  	  def check_login
  	  	render( json: {Error: "access denied"}, status: 401 ) unless current_user
  	  end
  	end
  end
end

app/controllers/api/v1/books_controller.rb
module Api
  module V1
  	class BooksController < ::Api::V1::BaseController
  	  def lookup
  	    render json: books
  	  end

  	  private

  	  def books
  		Book.includes(:category).map do |book|
  		  book.attributes.slice('title', 'isbn')
  		    .merge(category_name: book.category_name)
  		    .symbolize_keys
  		end	
  	  end
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_books, only: :index
  before_action :load_book, only: :show
  before_action :new_book, only: :create
  before_action :reservations_handler, only: :show

  def create
    if new_book.save
      redirect_to books_path
    else
      redirect_to new_book_path
    end
  end

  def filter
    render template: 'books/filter', locals: { books: filter_books }
  end

  def show
  end

  def reservations_handler
    @reservations_handler ||= ReservationsHandler.new(current_user, load_book)
  end

  private

  def filter_params
    permitted_params
      .slice(:title, :isbn)
      .merge(category.present? ? { category_id: category.id } : {})
      .reject{ |k, v| v.to_s.empty? }
  end

  def filter_books
    Book.where(filter_params)
  end

  def category
    Category.find_by(name: permitted_params[:category_name])
  end

  def load_books
    @books = Book.all
  end

  def load_book
    @book = Book.find(params[:id])
  end

  def new_book
    @book = Book.new(title: params[:title], isbn: params[:isbn], category_name: params[:category_name])
  end

  def permitted_params
    params.permit(:title, :isbn, :category_id, :category_name)
  end
end

app/controllers/google_books_controller.rb
class GoogleBooksController < ApplicationController
  def show
    render json: volume_info.to_json
  end

  private

  def volume_info
    total_items.to_i > 0 ? items[0].fetch('volumeInfo', '') : {}
  end

  def items
    google_books_api_response['items']
  end

  def total_items
    book_info_hash_data['totalItems']
  end

  def book_info_hash_data
    google_books_api_response.to_hash
  end

  def google_books_api_response
    HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{params[:isbn]}")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :load_user, only: [:users_reservations]

  def reserve
    reservations_handler.reserve if reservations_handler.can_reserve?
    redirect_to(book_path(book.id))
  end

  def take
    reservations_handler.take if reservations_handler.can_take?
    redirect_to(book_path(book.id))
  end

  def give_back
    reservations_handler.give_back if reservations_handler.can_give_back?
    redirect_to(book_path(book.id))
  end

  def cancel
    reservations_handler.cancel_reservation
    redirect_to(book_path(book.id))
  end

  def users_reservations
  end

  private

  def reservations_handler
    @reservations_handler ||= ReservationsHandler.new(current_user, book)
  end

  def book
    @book ||= Book.find(params[:book_id])
  end

  def load_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    fromOmniAuthGetter = UserFromOmniauthGetter.new(request.env['omniauth.auth'])
    @user = fromOmniAuthGetter.perform

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # all users
  end

  def show
    # profil usera
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/elements/_action.html.erb
<% if @reservations_handler.can_take? %>
  <%= link_to('Take', take_book_path(book_id: book.id), class: 'btn') %>
<% elsif @reservations_handler.can_give_back? %>
  <%= link_to('Give back', give_back_book_path(book_id: book.id), class: 'btn') %>
<% elsif @reservations_handler.can_reserve? %>
  <%= link_to('Make reservation', reserve_book_path(book_id: book.id), class: 'btn') %>
<% else %>
  <%= link_to('Cancel reservation', cancel_book_reservation_path(book_id: book.id), class: 'btn') %>
<% end %>

app/views/books/elements/_find_books.html.erb
<%= form_tag filter_path, class: 'search_form', method: :get, remote: true, format: :js do %>
  <%= text_field_tag :isbn, '', placeholder: 'ISBN', class: 'x-autocomplete' %>
  <%= text_field_tag :title, '', placeholder: 'title', class: 'x-autocomplete' %>
  <%= text_field_tag :category_name, '', placeholder: 'category', class: 'x-autocomplete' %>
  <%= button_tag type: 'submit', class: 'btn' do %>
    <i class="fa fa-search"></i>
    lookup
  <% end %>
<% end %>
<br>

app/views/books/elements/_reservations.html.erb
<table>
  <thead>
    <tr>
      <th>status</th>
      <th>created</th>
      <th>expires</th>
      <th>user</th>
    </tr>
  </thead>
  <tbody>
    <% reservations.order(created_at: :desc).each do |reservation| %>
      <tr>
        <td class='book-status book-status--<%= reservation.status.underscore %>'><%= reservation.status %></td>
        <td><%= reservation.created_at.to_date %></td>
        <td><%= reservation.expires_in %></td>
        <td><%= reservation.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/elements/_table.html.erb
<div class='x-books-table-container'>
  <table>
    <thead>
      <tr>
        <th>title</th>
        <th>ISBN</th>
        <th>category</th>
        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.isbn %></td>
          <td><%= book.category_name %></td>
          <td><%= link_to('show', book_path(book.id)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to new_book_path, class: 'btn' do %>
    <i class="fa fa-plus-circle"></i>
    add book
  <% end %>
</div>

app/views/books/filter.js.erb
$('.x-books-table-container').html("<%= j( render partial: 'books/elements/table', locals: {books: books } ) %>")

app/views/books/index.html.erb
<main class="main-content">
  <h2>Books</h2>
  <%= render partial: 'books/elements/find_books' %>
  <%= render partial: 'books/elements/table', locals: {books: @books} %>
</main>

app/views/books/new.html.erb
<div class="basic-form">
  <h2>New book</h2>
  <%= form_tag books_path, method: :post do %>
    <div class="field field-link x-isbn">
      <%= text_field_tag 'isbn', '', placeholder: 'isbn' %>
      <%= link_to 'get info', '#', class: 'x-get-book-info-from-google-books get-info' %>
    </div>

    <div class="field x-title">
      <%= text_field_tag 'title', '', placeholder: 'title', autofocus: true %>
    </div>

    <div class="field x-category-name">
      <%= text_field_tag 'category_name', '', placeholder: 'category' %>
    </div>

    <div class="field x-page-count">
      <%= number_field_tag 'page_count', '', placeholder: 'pages count' %>
    </div>

    <div class="field x-published-date">
      <%= text_field_tag 'published_date', '', placeholder: 'published date (yyyy-mm-dd or yyyy)' %>
    </div>

    <%= button_tag type: 'submit', class: 'btn' do %>
      <i class="fa fa-check"></i>
      save
    <% end %>

    <%= link_to books_path, class: 'btn btn--cancel' do %>
      cancel
    <% end %>

  <% end %>
</div>

app/views/books/show.html.erb
<main class="main-content">
  <h2>"<%= @book.title %>"</h2>
  <p class="isbn-nr">isbn: <strong><%= @book.isbn %></strong></p>
  <% unless @book.reservations.empty? %>
    <%= render partial: 'books/elements/reservations', locals: {reservations: @book.reservations} %>
  <% end %>
  <%= render partial: 'books/elements/action', locals: {book: @book} %>
  <%= link_to books_path, class: 'back-link' do %>
    <i class="fa fa-angle-double-left"></i>
    return to books
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atelier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://use.fontawesome.com/df674ca52b.js"></script>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/reservations/users_reservations.html.erb
<main class="main-content">
  <h2><%= @user.email %></h2>
  <% if @user.reservations.active.any? %>
    <h3>reservations:</h3>
    <table>
      <thead>
        <tr>
          <th>status</th>
          <th>title</th>
          <th>expires</th>
        </tr>
      </thead>
      <tbody>
        <% @user.reservations.active.each do |reservation| %>
          <tr>
            <td class='book-status book-status--<%= reservation.status.underscore %>'><%= reservation.status %></td>
            <td><%= reservation.book.title %></td>
            <td><%= reservation.expires_in %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    user does not have reservations
  <% end %>

  <% if @user.reservations.completed.any? %>
    <h3>completed:</h3>
    <table>
      <thead>
        <tr>
          <th>title</th>
        </tr>
      </thead>
      <tbody>
        <% @user.reservations.completed.each do |reservation| %>
          <tr>
            <td><%= reservation.book.title %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</main>

app/views/shared/_header.html.erb
<header class='main-header'>
  <%= link_to root_path, class: 'brand' do %>
    <i class="fa fa-book" aria-hidden="true"></i> Atelier
  <% end %>
  <% if current_user %>
    <div class="user-data">
      <ul class="user-data__nav">
        <li><%= link_to 'edit', edit_user_registration_path %></li>
        <li><%= link_to 'my reservations', users_reservations_path(current_user.id)  %></li>
      </ul>
      <span class="user-data__user"><%= current_user.email %></span>
      <%= button_to('log out', destroy_user_session_path, method: :delete, class: "btn btn--logout") %>
    </div>
  <% end %>
</header>